### ISSUE TITLE
现在有的算法计算瓶颈在哪里？

### ISSUE THREAD

**Issue by hanayashiki** [mickeystroller/HiExpan#4]
很感谢你上次及时回复我的 issue，你们的方法很棒，非常 impressive
但是我在运行 dblp 和 wiki 的数据集时，运行的结果非常不错，但是有个问题就是计算的时间太长了，考虑到做实验的时候可能不会特别注意优化的问题，我想请教一下有没有哪里值得研究一下优化，谢谢

**Comment by mickeysjm** [comment]
I think the main limitation could be the iteration width expansion. When the tree is big and there are many nodes (under the same parent node), it takes quite a long time to do width expansion (basically this is set expansion) and it will be slow. You might replace the width expansion module with some one-time entity ranking methods (e.g., embedding based similarity search) and I expect this can significantly speed the entire framework up.
