### ISSUE TITLE
missing indent

### ISSUE THREAD

**Issue by JieyuZ2** [mickeystroller/HiExpan#5]
Hi Jiaming,

In HiExpan/src/SetExpan-new/set_expan_standalone.py, line 89-90 need indents otherwise the redundant feature will not be filtered out. Thanks!

Best,
Jieyu

**Comment by mickeysjm** [comment]
Thanks for pointing this out. I fix it in the commit: https://github.com/mickeystroller/HiExpan/commit/84faf9c824360dc21e5b816b1283016af398fec7
